// Code generated by MockGen. DO NOT EDIT.
// Source: internal/providers/firestore/document.go
//
// Generated by this command:
//
//	mockgen -source=internal/providers/firestore/document.go -destination=internal/providers/firestore/document_mock.go -package=firestore
//
// Package firestore is a generated GoMock package.
package firestore

import (
	context "context"
	reflect "reflect"

	firestore "cloud.google.com/go/firestore"
	gomock "go.uber.org/mock/gomock"
)

// MockDocumentRef is a mock of DocumentRef interface.
type MockDocumentRef struct {
	ctrl     *gomock.Controller
	recorder *MockDocumentRefMockRecorder
}

// MockDocumentRefMockRecorder is the mock recorder for MockDocumentRef.
type MockDocumentRefMockRecorder struct {
	mock *MockDocumentRef
}

// NewMockDocumentRef creates a new mock instance.
func NewMockDocumentRef(ctrl *gomock.Controller) *MockDocumentRef {
	mock := &MockDocumentRef{ctrl: ctrl}
	mock.recorder = &MockDocumentRefMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocumentRef) EXPECT() *MockDocumentRefMockRecorder {
	return m.recorder
}

// Collection mocks base method.
func (m *MockDocumentRef) Collection(path string) CollectionRef {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collection", path)
	ret0, _ := ret[0].(CollectionRef)
	return ret0
}

// Collection indicates an expected call of Collection.
func (mr *MockDocumentRefMockRecorder) Collection(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collection", reflect.TypeOf((*MockDocumentRef)(nil).Collection), path)
}

// Delete mocks base method.
func (m *MockDocumentRef) Delete(ctx context.Context, opts ...firestore.Precondition) (*firestore.WriteResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*firestore.WriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDocumentRefMockRecorder) Delete(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDocumentRef)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockDocumentRef) Get(ctx context.Context) (*firestore.DocumentSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*firestore.DocumentSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDocumentRefMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDocumentRef)(nil).Get), ctx)
}

// Reference mocks base method.
func (m *MockDocumentRef) Reference() *firestore.DocumentRef {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reference")
	ret0, _ := ret[0].(*firestore.DocumentRef)
	return ret0
}

// Reference indicates an expected call of Reference.
func (mr *MockDocumentRefMockRecorder) Reference() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reference", reflect.TypeOf((*MockDocumentRef)(nil).Reference))
}

// Set mocks base method.
func (m *MockDocumentRef) Set(ctx context.Context, data any, opts ...firestore.SetOption) (*firestore.WriteResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, data}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(*firestore.WriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockDocumentRefMockRecorder) Set(ctx, data any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, data}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockDocumentRef)(nil).Set), varargs...)
}
