// Code generated by MockGen. DO NOT EDIT.
// Source: write_batch.go
//
// Generated by this command:
//
//	mockgen -source=write_batch.go -destination=write_batch_mock.go -package=firestore
//
// Package firestore is a generated GoMock package.
package firestore

import (
	context "context"
	reflect "reflect"

	firestore "cloud.google.com/go/firestore"
	gomock "go.uber.org/mock/gomock"
)

// MockWriteBatch is a mock of WriteBatch interface.
type MockWriteBatch struct {
	ctrl     *gomock.Controller
	recorder *MockWriteBatchMockRecorder
}

// MockWriteBatchMockRecorder is the mock recorder for MockWriteBatch.
type MockWriteBatchMockRecorder struct {
	mock *MockWriteBatch
}

// NewMockWriteBatch creates a new mock instance.
func NewMockWriteBatch(ctrl *gomock.Controller) *MockWriteBatch {
	mock := &MockWriteBatch{ctrl: ctrl}
	mock.recorder = &MockWriteBatchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriteBatch) EXPECT() *MockWriteBatchMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockWriteBatch) Commit(ctx context.Context) ([]*firestore.WriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx)
	ret0, _ := ret[0].([]*firestore.WriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commit indicates an expected call of Commit.
func (mr *MockWriteBatchMockRecorder) Commit(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockWriteBatch)(nil).Commit), ctx)
}

// Create mocks base method.
func (m *MockWriteBatch) Create(docRef *firestore.DocumentRef, data any) WriteBatch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", docRef, data)
	ret0, _ := ret[0].(WriteBatch)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWriteBatchMockRecorder) Create(docRef, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWriteBatch)(nil).Create), docRef, data)
}

// Delete mocks base method.
func (m *MockWriteBatch) Delete(docRef *firestore.DocumentRef, preconds ...firestore.Precondition) WriteBatch {
	m.ctrl.T.Helper()
	varargs := []any{docRef}
	for _, a := range preconds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(WriteBatch)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWriteBatchMockRecorder) Delete(docRef any, preconds ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{docRef}, preconds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWriteBatch)(nil).Delete), varargs...)
}

// Set mocks base method.
func (m *MockWriteBatch) Set(docRef *firestore.DocumentRef, data any, opts ...firestore.SetOption) WriteBatch {
	m.ctrl.T.Helper()
	varargs := []any{docRef, data}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(WriteBatch)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockWriteBatchMockRecorder) Set(docRef, data any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{docRef, data}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockWriteBatch)(nil).Set), varargs...)
}

// Update mocks base method.
func (m *MockWriteBatch) Update(docRef *firestore.DocumentRef, updates []firestore.Update, preconds ...firestore.Precondition) WriteBatch {
	m.ctrl.T.Helper()
	varargs := []any{docRef, updates}
	for _, a := range preconds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(WriteBatch)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockWriteBatchMockRecorder) Update(docRef, updates any, preconds ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{docRef, updates}, preconds...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWriteBatch)(nil).Update), varargs...)
}
